# Generated by Django 6.1 on 2026-08-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(help_text='CPU Usage Percentage')),
                ('memory_usage', models.FloatField(help_text='Memory/RAM Usage Percentage')),
                ('disk_usage', models.FloatField(help_text='Disk Space Usage Percentage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Server Health Log',
                'verbose_name_plural': 'Server Health Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
