# Generated by Django 6.1 on 2026-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_serverhealthlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhealthlog',
            name='active_connections',
            field=models.IntegerField(default=0, help_text='Active network/DB connections'),
        ),
        migrations.AddField(
            model_name='serverhealthlog',
            name='system_uptime',
            field=models.CharField(default='N/A', help_text='Server Uptime', max_length=100),
        ),
    ]
