# Generated by Django 6.1 on 2026-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_serverhealthlog_active_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
