# Generated by Django 6.1 on 2026-09-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_commentattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={},
        ),
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='comment',
            new_name='body',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_email_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
