# Generated by Django 5.2.4 on 2026-09-01 17:03

import apps.clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal or display name of the client.', max_length=255, unique=True)),
                ('code', models.SlugField(blank=True, help_text='Short, URL-safe identifier. Auto-generated from name if left blank.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Bare domain without scheme, e.g. acme.com', max_length=253)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_domains', to='clients.client')),
            ],
            options={
                'verbose_name': 'Whitelisted Domain',
                'verbose_name_plural': 'Whitelisted Domains',
                'ordering': ['domain_name'],
                'unique_together': {('client', 'domain_name')},
            },
        ),
        migrations.CreateModel(
            name='WhitelistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_cidr', models.CharField(help_text='IPv4/IPv6 address or CIDR range, e.g. 10.0.0.0/24.', max_length=50, validators=[apps.clients.models.validate_ip_or_cidr])),
                ('description', models.CharField(blank=True, help_text="Optional label for this entry, e.g. 'Head-office network'.", max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_ips', to='clients.client')),
            ],
            options={
                'verbose_name': 'Whitelisted IP / CIDR',
                'verbose_name_plural': 'Whitelisted IPs / CIDRs',
                'ordering': ['ip_or_cidr'],
                'unique_together': {('client', 'ip_or_cidr')},
            },
        ),
    ]
