# Generated by Django 6.1 on 2026-09-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_tenant_whitelist_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enforce_whitelisting',
            field=models.BooleanField(default=True, help_text='If True, strictly block non-whitelisted access. If False (Grace Mode), log the attempt but allow access.'),
        ),
        migrations.CreateModel(
            name='AccessAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(default='/', max_length=255)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='clients.client')),
            ],
            options={
                'verbose_name': 'Access Attempt Log',
                'verbose_name_plural': 'Access Attempt Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
