# Generated by Django 6.1 on 2026-09-16 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_enforce_whitelisting_accessattemptlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedEmergencyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(help_text='Purpose, e.g. "VPS Down / VPN Down"', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_emergency_emails', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_emergency_emails', to='clients.client')),
            ],
            options={
                'verbose_name': 'Whitelisted Emergency Email',
                'verbose_name_plural': 'Whitelisted Emergency Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
